language: go

go:
    - "1.11.x"
    - "1.12.x"

sudo: false
install: false

script:
    - env GO111MODULE=on make

after_success:
    - echo "Build Successful!" 
after_failure:
    - echo "Build Failed!" 

